{ pkgs, lib, config, ... }:
let
  user = "lehatown-server";
  podman = "${pkgs.podman}/bin/podman";
in {
  options.lehatown = { enable = lib.mkEnableOption "Enable lehatown"; };

  config = lib.mkIf config.lehatown.enable {
    services.podman.enable = true;

    services.podman.containers."stationeers-server-ui" = {
      inherit user;

      image = "ghcr.io/steamserverui/stationeersserverui:latest";
      volumes = [
        "/home/${user}/stationeers-lehatown/UIMod/config:/app/UIMod/config:rw"
        "/home/${user}/stationeers-lehatown/UIMod/tls:/app/UIMod/tls:rw"
        "/home/${user}/stationeers-lehatown/saves:/app/saves:rw"
        "lehatown_app-data:/app:rw"
      ];

      ports = [
        "8443:8443/tcp"
        "27016:27016/udp"
        "27016:27016/tcp"
        "27017:27017/udp"
        "27017:27017/tcp"
      ];

      extraPodmanArgs = [
        "--cpus=2"
        "--memory=11811160064b"
        "--network-alias=stationeers-server-ui"
        "--network=lehatown_default"
      ];
    };

    systemd.user.services."podman-stationeers-server-ui" = {
      Unit = {
        Description = "SSUI service";
        PartOf = [ "podman-compose-lehatown-root.target" ];
        Requires = [
          "podman-network-lehatown_default.service"
          "podman-volume-lehatown_app-data.service"
        ];
        After = [
          "podman-network-lehatown_default.service"
          "podman-volume-lehatown_app-data.service"
        ];
      };

      Install.WantedBy = [ "podman-compose-lehatown-root.target" ];
      Service.Restart = "always";
    };

    # Networks
    systemd.user.services."podman-network-lehatown_default" = let
      script = pkgs.writeShellScript "lehatown-network-create" ''
        ${podman} network inspect lehatown_default || ${podman} network create lehatown_default
      '';
    in {
      Service = {
        Type = "oneshot";
        RemainAfterExit = true;
        Exec = "${script}/bin/lehatown-network-create";
        ExecStop = "podman network rm -f lehatown_default";
      };

      Install.WantedBy = [ "podman-compose-lehatown-root.target" ];
      Unit.PartOf = [ "podman-compose-lehatown-root.target" ];
    };

    # Volumes
    systemd.user.services."podman-volume-lehatown_app-data" = let
      script = pkgs.writeShellScript "lehatown-volume-create" ''
        ${podman} volume inspect lehatown_app-data || ${podman} volume create lehatown_app-data
      '';
    in {
      Service = {
        Type = "oneshot";
        RemainAfterExit = true;
        Exec = "${script}/bin/lehatown-volume-create";
      };

      Install.WantedBy = [ "podman-compose-lehatown-root.target" ];
      Unit.PartOf = [ "podman-compose-lehatown-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.user.targets."podman-compose-lehatown-root" = {
      Unit.Description = "Root target generated by compose2nix.";
      Install.WantedBy = [ "multi-user.target" ];
    };
  };
}
